version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_code_igniter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - memcached
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - app-network

  db:
    image: mariadb:10.11
    container_name: codeigniter_blog_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codeigniter_blog_db
      MYSQL_USER: app_user_blog
      MYSQL_PASSWORD: app_password_blog
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge